/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    This file pulls in all the Juce source code, and builds it using the settings
    defined in AppConfig.h.

    If you want to change the method by which Juce is linked into your app, use the
    Jucer to change it, rather than trying to edit this file directly.

*/

#include "AppConfig.h"
#if defined (JUCER_LINUX_MAKE_7346DA2A)
 #include "../../../../JuceLibraryCode/amalgamation/juce_amalgamated1.cpp"
#elif defined (JUCER_XCODE_MAC_F6D2F4CF)
 #include "../../../../../JuceLibraryCode/amalgamation/juce_amalgamated1.cpp"
#endif
