#!/bin/sh
# postinst script for Open Ephys

if [ "$1" = configure ]; then

    echo "Copying open-ephys udev rules and restaring udev service..."
    cd /usr/local/bin
    mv open-ephys-gui/*.rules /etc/udev/rules.d
    service udev restart

    echo "Creating open-ephys symlink to /usr/local/bin..."
    ln -sf open-ephys-gui/open-ephys open-ephys

    echo "Ensuring desktop entry permissions..."
    chmod 644 /usr/share/applications/open-ephys.desktop
    
    echo "Updating desktop database..."
    update-desktop-database -q

    echo "Installation finished!"

fi

