/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#ifndef __MAINWINDOW_H_BA75E17__
#define __MAINWINDOW_H_BA75E17__

#include "../JuceLibraryCode/JuceHeader.h"
#include "UI/UIComponent.h"
#include "Audio/AudioComponent.h"
#include "Processors/ProcessorGraph.h"

//==============================================================================
class MainWindow   : public DocumentWindow
{
public:
    //==============================================================================
    MainWindow();
    ~MainWindow();

    void closeButtonPressed();

private:
    //==============================================================================
  
    void saveWindowBounds();
    void loadWindowBounds();

   // ScopedPointer <UIComponent> uiComponent;
   AudioComponent* audioComponent;
   ProcessorGraph* processorGraph;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainWindow)

};


#endif  // __MAINWINDOW_H_BA75E17__
